export const AgentStatus = {
  UNREGISTERED: "UNREGISTERED",
  DEFAULT: "DEFAULT",
  CALL_INCOMING: "CALL_INCOMING",
  CALL_CONNECTING: "CALL_CONNECTING",
  CALL_IN_PROGRESS: "CALL_IN_PROGRESS",
  CALL_CONFIRMED: "CALL_CONFIRMED",
  CALL_TERMINATED: "CALL_TERMINATED",
};
